### ISSUE TITLE
Panic: repeated read on failed websocket connection

### ISSUE THREAD

**Issue by aitva** [slack-go/slack#338]
Hello,

Thank you for this library, I have been using it for more than a year and it was working flawlessly. But, since last week the library is panicking:

```
panic: repeated read on failed websocket connection

goroutine 227 [running]:
github.com/aitva/bot/vendor/github.com/gorilla/websocket.(*Conn).NextReader(0xc420532dc0, 0xffffffffffffffff, 0x0, 0xc42004cec8, 0xc42004cec8, 0x412198)
        /go/src/github.com/aitva/bot/vendor/github.com/gorilla/websocket/conn.go:958 +0x35d
github.com/aitva/bot/vendor/github.com/gorilla/websocket.(*Conn).ReadJSON(0xc420532dc0, 0x8ece60, 0xc4203bd1a0, 0x9edbe0, 0xc4a660)
        /go/src/github.com/aitva/bot/vendor/github.com/gorilla/websocket/json.go:45 +0x2f
github.com/aitva/bot/vendor/github.com/nlopes/slack.(*RTM).receiveIncomingEvent(0xc420533180)
        /go/src/github.com/aitva/bot/vendor/github.com/nlopes/slack/websocket_managed_conn.go:288 +0xa1
```

The panic occurs after receiving a bunch of `*slack.IncomingEventError` with the error `websocket: close 1006 (abnormal closure): unexpected EOF`.

```
SLACK 2018/06/15 05:54:55 team.go:221: ev=*slack.IncomingEventError err="websocket: close 1006 (abnormal closure): unexpected EOF"
SLACK 2018/06/15 05:54:55 team.go:221: ev=*slack.IncomingEventError err="websocket: close 1006 (abnormal closure): unexpected EOF"
SLACK 2018/06/15 05:54:55 team.go:221: ev=*slack.IncomingEventError err="websocket: close 1006 (abnormal closure): unexpected EOF"
SLACK 2018/06/15 05:54:55 team.go:221: ev=*slack.IncomingEventError err="websocket: close 1006 (abnormal closure): unexpected EOF"
SLACK 2018/06/15 05:54:55 team.go:221: ev=*slack.IncomingEventError err="websocket: close 1006 (abnormal closure): unexpected EOF"
SLACK 2018/06/15 05:54:55 team.go:221: ev=*slack.IncomingEventError err="websocket: close 1006 (abnormal closure): unexpected EOF"
SLACK 2018/06/15 05:54:55 team.go:221: ev=*slack.IncomingEventError err="websocket: close 1006 (abnormal closure): unexpected EOF"
SLACK 2018/06/15 05:54:55 team.go:221: ev=*slack.IncomingEventError err="websocket: close 1006 (abnormal closure): unexpected EOF"
[...]
```

I am in a difficult situation since I cannot recover from the panic (the panicky goroutine is started from `RTM::ManageConnection`) and I cannot force a reconnection since the `RTM::Reconnect` method is not implemented.

Do you know why this is happening? Do you have an idea of how I could avoid the panic? I can provide more information if needed.

**Comment by james-lawrence** [comment]
honestly? no idea, I've never seen this error and we run a bunch of managed RTM connections.

**Comment by james-lawrence** [comment]
is this still an issue in the master?

**Comment by pseidemann** [comment]
hi @james-lawrence,
I still have the same problem with version 0.2.0 8ab4d0b364ef1e9af5d102531da20d5ec902b6c4.
any chance there is already a fix for this in place which gets released soon?

**Comment by parsley42** [comment]
The read loop code has seen multiple changes since the 0.2.0 release. Time for a new release?
