### ISSUE TITLE
Go panic caused by call to handleIncomingEvents()

### ISSUE THREAD

**Issue by dieter-smt** [slack-go/slack#609]
Slack package is causing go panic from time to time. This is no persistent error, i.e. it usually works for a while (hours, sometimes days) but then go panic happens.

Go stack trace below:
```
2019-10-21T08:12:50.216418488Z panic: runtime error: slice bounds out of range
2019-10-21T08:12:50.216447141Z 
2019-10-21T08:12:50.216453542Z goroutine 10895 [running]:
2019-10-21T08:12:50.216459214Z bufio.(*Reader).Read(0xc000990480, 0xc000590ffc, 0xe04, 0xe04, 0x1fc, 0x0, 0x0)
2019-10-21T08:12:50.216465016Z 	/usr/local/go/src/bufio/bufio.go:234 +0x3c7
2019-10-21T08:12:50.216470494Z  /vendor/github.com/gorilla/websocket.(*messageReader).Read(0xc00000e088, 0xc000590ffc, 0xe04, 0xe04, 0x1fc, 0x0, 0x0)
2019-10-21T08:12:50.216483041Z 	/vendor/github.com/gorilla/websocket/conn.go:1021 +0x213
2019-10-21T08:12:50.216489743Z encoding/json.(*Decoder).refill(0xc000840420, 0x22, 0x0)
2019-10-21T08:12:50.216495291Z 	/usr/local/go/src/encoding/json/stream.go:159 +0xf8
2019-10-21T08:12:50.216500571Z encoding/json.(*Decoder).readValue(0xc000840420, 0x0, 0x0, 0xd6e6a0)
2019-10-21T08:12:50.2165308Z 	/usr/local/go/src/encoding/json/stream.go:134 +0x210
2019-10-21T08:12:50.216544402Z encoding/json.(*Decoder).Decode(0xc000840420, 0xca2520, 0xc0001a7380, 0xc00000e088, 0x0)
2019-10-21T08:12:50.21655035Z 	/usr/local/go/src/encoding/json/stream.go:63 +0x79
2019-10-21T08:12:50.216555296Z /vendor/github.com/gorilla/websocket.(*Conn).ReadJSON(0xc0009cc420, 0xca2520, 0xc0001a7380, 0x0, 0xc00099c800)
2019-10-21T08:12:50.216559989Z  /vendor/github.com/gorilla/websocket/json.go:54 +0xa7
2019-10-21T08:12:50.216564916Z /vendor/github.com/nlopes/slack.(*RTM).receiveIncomingEvent(0xc0001255f0, 0x0, 0x0)
2019-10-21T08:12:50.216570598Z  /vendor/github.com/nlopes/slack/websocket_managed_conn.go:341 +0xa3
2019-10-21T08:12:50.216576484Z /vendor/github.com/nlopes/slack.(*RTM).handleIncomingEvents(0xc0001255f0)
2019-10-21T08:12:50.216581924Z  /vendor/github.com/nlopes/slack/websocket_managed_conn.go:277 +0x2b
2019-10-21T08:12:50.216587208Z created by /vendor/github.com/nlopes/slack.(*RTM).ManageConnection
2019-10-21T08:12:50.216591588Z 	/vendor/github.com/nlopes/slack/websocket_managed_conn.go:62 +0x208
```

Code in line 62 in `websocket_managed_conn.go` is `go rtm.handleIncomingEvents()`

The comment for `func (rtm *RTM) ManageConnection()`. states it should be called only once per slack api. This is the case, logs confirm its actually called once.

This happens with v0.6.0 of the slack package

**Comment by kanata2** [comment]
It seems that a lot of time has passed.
So I close this now, but please feel free to re-open if you need.
