### ISSUE TITLE
Sending a response using PostMessage

### ISSUE THREAD

**Issue by Quotennial** [slack-go/slack#796]
Hi all, new to go and muddling my way through this great package. 

I'm trying to use the `PostMessage` method but come across this error: 
```go
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x127abb7]

goroutine 25 [running]:
github.com/slack-go/slack.(*Client).SendMessageContext(0x0, 0x13b6b20, 0xc000016070, 0xc000207c50, 0xb, 0xc00009bfa0, 0x2, 0x2, 0x0, 0x100e4a8, ...)
        /Users/user/go/src/github.com/slack-go/slack/chat.go:207 +0x57
github.com/slack-go/slack.(*Client).PostMessage(0x0, 0xc000207c50, 0xb, 0xc000094428, 0x1, 0x1, 0x1, 0x15, 0x0, 0x0, ...)
        /Users/user/go/src/github.com/slack-go/slack/chat.go:124 +0x11b
main.handleMessage(0xc000112500)
        /Users/user/pythoncode/sotw/main.go:35 +0x30e
created by main.main
        /Users/user/pythoncode/sotw/main.go:23 +0x153
exit status 2
```

I am at a loss how to debug this and would appreciate any help!

```go
package main

import (
	"fmt"
	"log"
	"os"

	"github.com/slack-go/slack"
)

var (
	slackClient *slack.Client //initialise the slack event
)

func main() {
	slackClient := slack.New(os.Getenv("SLACK_ACCESS_TOKEN"))
	rtm := slackClient.NewRTM() //create the realtime messaging objext
	go rtm.ManageConnection()   // set it up in a go routine

	for msg := range rtm.IncomingEvents {
		switch ev := msg.Data.(type) {
		case *slack.MessageEvent:
			go handleMessage(ev)
		}
	}
}

func handleMessage(ev *slack.MessageEvent) {
	fmt.Printf("%v\n", ev)
	fmt.Printf("Text Received: %v\n", ev.Msg.Text)
	_, _, err := slackClient.PostMessage(ev.Channel, slack.MsgOptionText("message", false), slack.MsgOptionAsUser(true))
	if err != nil {
		log.Println("error sending to slack: " + err.Error())
	}
	return
}
```

**Comment by kanata2** [comment]
This is not an issue of this library.
You can see the correct behavior when you use `=` operator instead of `:=` operator in `slackClient := slack.New(os.Getenv("SLACK_ACCESS_TOKEN"))`.

**Comment by Quotennial** [comment]
> This is not an issue of this library.
> You can see the correct behavior when you use `=` operator instead of `:=` operator in `slackClient := slack.New(os.Getenv("SLACK_ACCESS_TOKEN"))`.

Thank you very much
